---
#------------------------------------------------------------------------------
# Playbook to CREATE AWS demo environment. 
#------------------------------------------------------------------------------

- name: PROVISION VPC SUBNETS & F5 INSTANCES
  hosts: localhost
  connection: local
  gather_facts: no

  environment:
    AWS_ACCESS_KEY_ID: "{{ ec2_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ ec2_secret_key }}"
    AWS_REGION: "{{ aws_region }}"

    

#------------------------------------------------------------------------------
# Load Variables from files 
#------------------------------------------------------------------------------
  
  # You need to create a file named aws_creds.yaml (update path below) with the 
  # following variables:
  #
  #  ec2_access_key: "--your-key-here--"
  #  ec2_secret_key: "--your-secret-here--"
  #
  vars_files:
    - ../../creds/aws_creds.yaml
    - ../../creds/big_creds.yaml
    - ./vars/vars.yaml

#------------------------------------------------------------------------------
# End variables
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Start tasks
#------------------------------------------------------------------------------

  tasks:

  - include_tasks: ./tasks/tasks-01-aws-create-base-vpc.yaml
  - include_tasks: ./tasks/tasks-02-aws-create-vpc-peering.yaml
  - include_tasks: ./tasks/tasks-03-aws-create-cft.yaml
  - include_tasks: ./tasks/tasks-04-aws-create-as3.yaml
  - include_tasks: ./tasks/tasks-05-aws-outputs.yaml


#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------
...